local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 3.0
   inflation_radius: 0.15
   robot_radius: 0.2
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 1.0
   rolling_window: true

   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
   obstacle_layer:
      enabled: true
      observation_sources: scan
      min_obstacle_height: 0.0
      max_obstacle_height: 2.0

