obstacle_layer:

  obstacle_range: 2.0 # 2.0
  raytrace_range: 3.0 # 3.0

  observation_sources: scan

  scan:
    sensor_frame: scan_link
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  #inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true